[package]
name = "AquaOS-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "aqua-api","kernel-proc"]

[dependencies]
bootloader = "0.9"
kernel-proc = { path = "kernel-proc" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
