[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSSTEM:console"]

[build]
target = "x86_64_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"